spring:
  datasource:
    url: jdbc:mysql://localhost:3306/piaoliuping?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: 127.0.0.1
      port: 6379
logging:
  level:
    com.example: debug
  pattern:
    dateformat: HH:mm:ss

com:
  jwt:
    user-secret-key: chenabzjskwosladsxswsdaachenabzjskwosladsxswsdaa
    user-ttl: 7200000
    user-token-name: authentication